const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const nonempty=value=>typeof value==='string'&&value.trim().length>0;
const required=(value,keys)=>{if(!value||typeof value!=='object'||Array.isArray(value)||keys.some(key=>!own(value,key)))throw new Error('Faltan campos requeridos de evidencia.');};
const fail=message=>{throw new Error(message)};
const dateValid=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number(value.slice(0,4))>0&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;
const timestampValid=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)&&dateValid(value.slice(0,10))&&Number(value.slice(11,13))<24&&Number(value.slice(14,16))<60&&Number(value.slice(17,19))<60&&Number.isFinite(Date.parse(value));
export function validateBundle(bundle){
 if(!bundle||bundle.schema_version!=='1.0')fail('Versión de paquete no compatible (se requiere 1.0).');
 if(bundle.scenario_kind!=='published_snapshot')fail('El paquete debe contener posiciones publicadas.');
 for(const key of ['sources','observations','intentions','assertions','inventory','assumptions','unresolved_issues'])if(!Array.isArray(bundle[key]))fail(`Falta la sección ${key}.`);
 if(!nonempty(bundle.id)||!dateValid(bundle.report_date)||!bundle.review||!bundle.bundle_hash)fail('Faltan identificación, fecha o revisión del paquete.');
 if(bundle.sources.length<2||new Set(bundle.sources.map(s=>s.id)).size!==bundle.sources.length||!['position','vts'].every(id=>bundle.sources.some(s=>s.id===id))||bundle.sources.some(s=>s.status!=='verified'||!/^([a-f0-9]{64})$/i.test(s.sha256)))fail('Las fuentes requeridas deben estar verificadas.');
 required(bundle.review,['status']);
 if(!['approved','reviewed'].includes(bundle.review.status)||!/^([a-f0-9]{64})$/i.test(bundle.bundle_hash))fail('Revisión incompleta o hash de paquete inválido.');
 if(!bundle.metric_eligibility||typeof bundle.metric_eligibility!=='object'||Array.isArray(bundle.metric_eligibility)||Object.values(bundle.metric_eligibility).some(value=>typeof value!=='boolean'))fail('Elegibilidad de métricas ausente o inválida.');
 if(bundle.metric_eligibility)for(const [key,value] of Object.entries(bundle.metric_eligibility))if(value===true&&!['reported_vessel_count','reported_count','plan_count','coverage'].includes(key))fail('Métrica no permitida en evidencia publicada.');
 for(const key of ['assumptions','unresolved_issues'])if(!bundle[key].every(value=>typeof value==='string'))fail('Anotaciones de evidencia inválidas.');
 const start=Date.parse(bundle.coverage?.start),end=Date.parse(bundle.coverage?.end);if(!timestampValid(bundle.coverage?.start)||!timestampValid(bundle.coverage?.end)||end<start)fail('Cobertura temporal inválida.');
 required(bundle.coverage,['start','end','observation_cutoff']);if(bundle.coverage.observation_cutoff!==null)fail('El corte de observación debe permanecer desconocido.');
 for(const source of bundle.sources){required(source,['id','sha256','status','retrieved_at']);if(!nonempty(source.id)||!timestampValid(source.retrieved_at))fail('Fuente sin fecha de recuperación válida.');}
 if(bundle.review.schema_version!=null&&bundle.review.schema_version!==bundle.schema_version)fail('Versión de revisión incompatible.');
 if(own(bundle.review,'source_hashes')){required(bundle.review.source_hashes,['position','vts']);for(const source of bundle.sources)if(bundle.review.source_hashes[source.id]!==source.sha256)fail('Hash de revisión incompatible.');}
 for(const key of ['normalization_hash','review_hash','schema_hash'])if(bundle[key]!=null&&!/^[a-f0-9]{64}$/i.test(bundle[key]))fail('Hash adicional inválido.');
 const sources=new Set(bundle.sources.map(s=>s.id)),assertions=new Set();
 for(const a of bundle.assertions){required(a,['id','source_id','source_sha256','page','section','row','field','original_text','parsed_value','units','precision','quality_warnings','evidence','status','event_type']);if(!nonempty(a.id)||!Number.isInteger(a.page)||a.page<1||!Number.isInteger(a.row)||a.row<1||!nonempty(a.section)||!nonempty(a.field)||typeof a.original_text!=='string'||(a.units!==null&&typeof a.units!=='string')||(a.precision!==null&&!['date','datetime'].includes(a.precision))||(a.event_type!==null&&!['planned_pilot_time','planned_tug_time','movement_intention','narrative_intention','reported_berth_arrival','reported_anchorage_arrival'].includes(a.event_type))||!Array.isArray(a.quality_warnings)||!a.quality_warnings.every(w=>typeof w==='string')||a.source_sha256!==bundle.sources.find(s=>s.id===a.source_id)?.sha256||a.evidence!=='reported'||!['observation','planned','unknown'].includes(a.status))fail('Procedencia o estado de afirmación inválido.');if(!a.id||assertions.has(a.id)||!sources.has(a.source_id))fail('Afirmación duplicada o fuente desconocida.');assertions.add(a.id);}
 function checkTime(t){if(t==null)return;if(typeof t!=='object')fail('Tiempo sin precisión ni procedencia.');required(t,['original','precision','earliest','latest','timezone','timezone_evidence']);if(typeof t.original!=='string'||!['date','datetime'].includes(t.precision)||!nonempty(t.timezone)||!['assumed','confirmed'].includes(t.timezone_evidence))fail('Tiempo sin precisión ni procedencia.');const a=t.earliest==null?null:Date.parse(t.earliest),b=t.latest==null?null:Date.parse(t.latest);if((a!==null&&!timestampValid(t.earliest))||(b!==null&&!timestampValid(t.latest))||(a!==null&&b!==null&&b<a))fail('Intervalo temporal inválido.');}
 for(const key of ['observations','intentions','inventory']){const ids=new Set();for(const row of bundle[key]){if(key==='observations'||key==='intentions'){required(row,['id','name','terminal','assertion_ids']);if(!nonempty(row.name)||(row.terminal!==null&&!nonempty(row.terminal))||!Array.isArray(row.assertion_ids)||!row.assertion_ids.every(nonempty))fail('Registro sin nombre, terminal o referencias válidas.');}if(key==='observations'){required(row,['vessel_id','in_scope','state']);if(!nonempty(row.vessel_id)||typeof row.in_scope!=='boolean')fail('Identidad o alcance de observación inválido.');}if(key==='intentions'){required(row,['direction','pilot_time','tug_time','tugs']);if(!['ENTRADA','ZARPADA'].includes(row.direction)||!Array.isArray(row.tugs)||!row.tugs.every(nonempty))fail('Dirección o remolcadores inválidos.');}if(key==='inventory'){if(own(row,'assertion_ids')&&(!Array.isArray(row.assertion_ids)||!row.assertion_ids.every(nonempty)))fail('Referencias de inventario inválidas.');required(row,['source_id','page','section','row','original_text','disposition','review_status']);if(!Number.isInteger(row.page)||row.page<1||!Number.isInteger(row.row)||row.row<1||!nonempty(row.section)||typeof row.original_text!=='string'||!['parsed','retained-unparsed','excluded-with-reason'].includes(row.disposition)||!['reviewed','retained-context-reviewed','approved'].includes(row.review_status)||(row.disposition==='excluded-with-reason'&&!nonempty(row.reason)&&!nonempty(row.exclusion_reason)))fail('Inventario sin procedencia o disposición válida.');}if(!nonempty(row.id)||ids.has(row.id))fail(`ID inválido en ${key}.`);ids.add(row.id);for(const ref of row.assertion_ids??[])if(!assertions.has(ref))fail('Referencia de afirmación desconocida.');for(const k of ['length_m','beam_m','tonnage'])if(row[k]!=null&&(!Number.isFinite(row[k])||row[k]<=0))fail(`Valor numérico inválido: ${k}.`);for(const k of ['arrival_time','pilot_time','tug_time']){checkTime(row[k]);if(k!=='arrival_time'&&row[k]?.earliest!=null&&(Date.parse(row[k].earliest)<start||Date.parse(row[k].latest??row[k].earliest)>end))fail('Hito fuera de cobertura.');}if(key==='observations'&&!['reported-alongside','reported-anchorage','unknown'].includes(row.state))fail('Estado de observación desconocido.');if(key==='inventory'&&!sources.has(row.source_id))fail('Fuente de inventario desconocida.');}}
 return bundle;
}
export async function loadBundle(input,{signal}={}){let value;if(typeof input==='string'){const response=await fetch(input,signal?{signal}:undefined);if(!response.ok)fail(`No se pudo cargar el paquete (${response.status}). Ejecutá la adquisición y el ensamblado local.`);value=await response.json();}else if(input?.text)value=JSON.parse(await input.text());else value=input;return validateBundle(value);}
